apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.cilium.io
    chart: cilium
    targetRevision: "1.16.*"
    helm:
      valuesObject:
        kubeProxyReplacement: true
        k8sServiceHost: 192.168.1.101
        k8sServicePort: 6443
        hubble:
          enabled: true
          relay:
            enabled: true
          ui:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
