all:
  children:
    control_plane:
      hosts:
        host1:
          ansible_host: 10.10.10.10

    workers:
      hosts:
        host2:
          ansible_host: 10.10.10.20
        host3:
          ansible_host: 10.10.10.30

    k8s_cluster:
      children:
        control_plane:
        workers:
