all:
  children:
    control_plane:
      hosts:
        n150-cp:
          ansible_host: 192.168.1.101

    workers:
      hosts:
        ser5-worker-1:
          ansible_host: 192.168.1.102
        ser5-worker-2:
          ansible_host: 192.168.1.103

    k8s_cluster:
      children:
        control_plane:
        workers:
