---
- name: Add Kubernetes repo
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/rpm/
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/rpm/repodata/repomd.xml.key
      exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni

- name: Install kubeadm, kubelet, kubectl
  dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    disable_excludes: kubernetes

- name: Hold kubeadm, kubelet, kubectl (dnf versionlock)
  command: dnf versionlock add {{ item }}
  loop:
    - kubelet
    - kubeadm
    - kubectl
  changed_when: false

- name: Enable kubelet
  systemd:
    name: kubelet
    enabled: true
